### ISSUE TITLE
ProActiveWorkflowParser Issue 

### ISSUE THREAD

**Issue by gparanthoen** [ow2-proactive/workflow-catalog#30]
While I wanted to add the Workflow "file_trigger" from the template to the bucket "examples", I got the following error : 

```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: FOLDER_TO_MONITOR=/tmp and FOLDER_TO_MONITOR=/tmp
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at org.ow2.proactive.workflow_catalog.rest.util.ProActiveWorkflowParser.parse(ProActiveWorkflowParser.java:156)
	at org.ow2.proactive.workflow_catalog.rest.service.WorkflowRevisionService.createWorkflowRevision(WorkflowRevisionService.java:117)
	at org.ow2.proactive.workflow_catalog.rest.service.WorkflowRevisionService$$FastClassBySpringCGLIB$$e5af52f4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.ow2.proactive.workflow_catalog.rest.service.WorkflowRevisionService$$EnhancerBySpringCGLIB$$e5f2d873.createWorkflowRevision(<generated>)
	at org.ow2.proactive.workflow_catalog.rest.service.WorkflowService.createWorkflow(WorkflowService.java:66)
	at org.ow2.proactive.workflow_catalog.rest.service.BucketService.populateCatalog(BucketService.java:114)
	at org.ow2.proactive.workflow_catalog.rest.service.BucketService.init(BucketService.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 76 more

```

**Comment by fviale** [comment]
Good find, I think this is due to the fact that a variable with the same name and values is defined at both task and job level, but the catalog should handle better this case.

**Comment by laurentpellegrino** [comment]
Fixed by https://github.com/ow2-proactive/workflow-catalog/commit/3ee027f1aafdab54b76f85de1a4c2ed20fd25624.
